name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [genmon]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set version variable
        run: |
          VERSION="$(jq -r '.version' < ${{ matrix.addon }}/config.json)"
          echo "Version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          file: ./${{ matrix.addon }}/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-addons/${{ matrix.addon }}:latest
            ghcr.io/${{ github.repository_owner }}/ha-addons/${{ matrix.addon }}:${{ env.VERSION }}
